VERSION 0.7

jsdos:
    FROM node:16-alpine
    
    WORKDIR site
    RUN wget https://js-dos.com/6.22/current/js-dos.js && \
        wget https://js-dos.com/6.22/current/wdosbox.js && \
        wget https://js-dos.com/6.22/current/wdosbox.wasm.js
    RUN npm install -g serve

game:
    FROM +jsdos
    
    ARG GAME_URL
    RUN wget -O game.zip $GAME_URL

web:
    FROM +game

    ARG GAME_ARGS
    COPY index.html .
    RUN sed -i s/GAME_ARGS/$GAME_ARGS/ index.html

    ENTRYPOINT npx serve -l tcp://0.0.0.0:8000

play:
    LOCALLY

    ARG GAME_TAG
    WITH DOCKER --load jsdos:$GAME_TAG=+web
        RUN docker inspect jsdos:$GAME_TAG > /dev/null && \ #Using side-effect to save image locally too
            docker run --rm -p 127.0.0.1:8000:8000 jsdos:$GAME_TAG
    END

secretagent:
    BUILD \
        --build-arg GAME_TAG=secretagent \
        --build-arg GAME_URL=https://archive.org/download/SecretAgent_945/AGENT.ZIP \
        --build-arg GAME_ARGS=\"SAM1.EXE\" \
        +play

cosmo:
    BUILD \
        --build-arg GAME_TAG=cosmo \
        --build-arg GAME_URL=https://archive.org/download/CosmosCosmicAdventure/CosmosCosmicAdventure-ForbiddenPlanet-Adventure1Of3V1.20sw1992apogeeSoftwareLtd.action.zip \
        --build-arg GAME_ARGS=\"COSMO1.EXE\" \
        +play

doom:
    BUILD \
        --build-arg GAME_TAG=doom \
        --build-arg GAME_URL=https://archive.org/download/DoomsharewareEpisode/doom.ZIP \
        --build-arg GAME_ARGS=\"DOOM.EXE\" \
        +play

dugeonmaster:
    BUILD \
        --build-arg GAME_TAG=dugeonmaster \
        --build-arg GAME_URL=https://d2.myabandonware.com/t/597644be-8aa2-49de-8a21-fa6455a8f379/Dungeon-Master_DOS_EN.zip \
        --build-arg GAME_ARGS=\"DUGEON-MASTER,DMASTER,DM.EXE\" \
        +play


scorch:
    BUILD \
        --build-arg GAME_TAG=scorch \
        --build-arg GAME_URL=https://archive.org/download/msdos_festival_SCORCH15/SCORCH15.ZIP \
        --build-arg GAME_ARGS=\"SCORCH.EXE\" \
        +play

keen:
    BUILD \
        --build-arg GAME_TAG=keen \
        --build-arg GAME_URL=https://image.dosgamesarchive.com/games/keen-shr.zip \
        --build-arg GAME_ARGS=\"KEEN.BAT\" \
        +play

zeliard:
    BUILD \
       --build-arg GAME_TAG=zeliard \
       --build-arg GAME_URL=https://d2.myabandonware.com/t/155805d6-fb4a-4a4d-b61d-aa11ce3833ec/Zeliard_DOS_EN.zip \
       --build-arg GAME_ARGS=\"ZELIAD\" \
       +play